declare const classNames: {
  readonly wrapper: 'wrapper'
  readonly top: 'top'
  readonly back: 'back'
  readonly title: 'title'
  readonly switchWrapper: 'switchWrapper'
  readonly switch: 'switch'
  readonly element: 'element'
  readonly active: 'active'
  readonly formWrapper: 'formWrapper'
  readonly form: 'form'
  readonly group: 'group'
  readonly label: 'label'
  readonly dateTime: 'dateTime'
  readonly button: 'button'
}
export default classNames
export type ClassNames =
  | 'wrapper'
  | 'top'
  | 'back'
  | 'title'
  | 'switchWrapper'
  | 'switch'
  | 'element'
  | 'active'
  | 'formWrapper'
  | 'form'
  | 'group'
  | 'label'
  | 'dateTime'
  | 'button'
