declare const classNames: {
  readonly wrapper: 'wrapper'
  readonly top: 'top'
  readonly btn: 'btn'
  readonly left: 'left'
  readonly title: 'title'
  readonly storeInfo: 'storeInfo'
  readonly primaryName: 'primaryName'
  readonly secondaryName: 'secondaryName'
  readonly info: 'info'
  readonly listWrapper: 'listWrapper'
  readonly purchases: 'purchases'
  readonly row: 'row'
  readonly selected: 'selected'
  readonly icon: 'icon'
  readonly value: 'value'
  readonly positive: 'positive'
  readonly negative: 'negative'
  readonly action: 'action'
  readonly store: 'store'
  readonly date: 'date'
}
export default classNames
export type ClassNames =
  | 'wrapper'
  | 'top'
  | 'btn'
  | 'left'
  | 'title'
  | 'storeInfo'
  | 'primaryName'
  | 'secondaryName'
  | 'info'
  | 'listWrapper'
  | 'purchases'
  | 'row'
  | 'selected'
  | 'icon'
  | 'value'
  | 'positive'
  | 'negative'
  | 'action'
  | 'store'
  | 'date'
