declare const classNames: {
  readonly wrapper: 'wrapper'
  readonly accountInfo: 'accountInfo'
  readonly card: 'card'
  readonly top: 'top'
  readonly number: 'number'
  readonly balanceWrapper: 'balanceWrapper'
  readonly balance: 'balance'
  readonly name: 'name'
  readonly value: 'value'
  readonly negative: 'negative'
  readonly untilReset: 'untilReset'
  readonly limitInfo: 'limitInfo'
  readonly group: 'group'
  readonly buttons: 'buttons'
  readonly listWrapper: 'listWrapper'
  readonly actionsList: 'actionsList'
  readonly row: 'row'
  readonly selected: 'selected'
  readonly icon: 'icon'
  readonly positive: 'positive'
  readonly info: 'info'
  readonly action: 'action'
  readonly store: 'store'
  readonly date: 'date'
  readonly navbar: 'navbar'
}
export default classNames
export type ClassNames =
  | 'wrapper'
  | 'accountInfo'
  | 'card'
  | 'top'
  | 'number'
  | 'balanceWrapper'
  | 'balance'
  | 'name'
  | 'value'
  | 'negative'
  | 'untilReset'
  | 'limitInfo'
  | 'group'
  | 'buttons'
  | 'listWrapper'
  | 'actionsList'
  | 'row'
  | 'selected'
  | 'icon'
  | 'positive'
  | 'info'
  | 'action'
  | 'store'
  | 'date'
  | 'navbar'
