/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
declare const identifiersMap: CssIdentifiersMap

export default identifiersMap

export type CssIdentifiersMap = {
  card: string
  italic: string
  'text-h3': string
  'text-h4': string
  'text-h5': string
  'text-h6': string
  'text-subtitles': string
}
